insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (1, 1, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (2, 2, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (3, 3, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (4, 4, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (5, 5, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (6, 6, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (7, 7, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (8, 8, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (9, 9, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (10, 10, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (11, 11, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (12, 12, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (13, 13, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (14, 14, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (15, 15, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (16, 16, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (17, 17, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (18, 18, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (19, 19, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (20, 20, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (21, 21, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (22, 22, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (23, 23, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (24, 24, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (25, 25, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (26, 26, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (27, 27, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (28, 28, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (29, 29, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (30, 30, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (31, 31, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (32, 32, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (33, 33, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (34, 34, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (35, 35, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (36, 36, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (37, 37, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (38, 38, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (39, 39, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (40, 40, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (41, 41, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (42, 42, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (43, 43, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (44, 44, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (45, 45, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (46, 46, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (47, 47, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (48, 48, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (49, 49, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (50, 50, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (51, 51, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (52, 52, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (53, 53, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (54, 54, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (55, 55, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (56, 56, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (57, 57, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (58, 58, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (59, 59, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (60, 60, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (61, 61, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (62, 62, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (63, 63, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (64, 64, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (65, 65, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (66, 66, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (67, 67, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (68, 68, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (69, 69, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (70, 70, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (71, 71, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (72, 72, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (73, 73, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (74, 74, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (75, 75, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (76, 76, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (77, 77, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (78, 78, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (79, 79, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (80, 80, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (81, 81, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (82, 82, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (83, 83, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (84, 84, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (85, 85, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (86, 86, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (87, 87, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (88, 88, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (89, 89, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (90, 90, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (91, 91, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (92, 92, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (93, 93, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (94, 94, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (95, 95, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (96, 96, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (97, 97, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (98, 98, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (99, 99, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (100, 100, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (101, 101, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (102, 102, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (103, 103, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (104, 104, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (105, 105, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (106, 106, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (107, 107, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (108, 108, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (109, 109, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (110, 110, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (111, 111, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (112, 112, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (113, 113, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (114, 114, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (115, 115, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (116, 116, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (117, 117, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (118, 118, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (119, 119, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (120, 120, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (121, 121, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (122, 122, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (123, 123, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (124, 124, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (125, 125, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (126, 126, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (127, 127, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (128, 128, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (129, 129, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (130, 130, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (131, 131, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (132, 132, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (133, 133, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (134, 134, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (135, 135, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (136, 136, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (137, 137, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (138, 138, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (139, 139, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (140, 140, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (141, 141, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (142, 142, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (143, 143, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (144, 144, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (145, 145, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (146, 146, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (147, 147, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (148, 148, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (149, 149, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (150, 150, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (151, 151, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (152, 152, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (153, 153, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (154, 154, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (155, 155, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (156, 156, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (157, 157, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (158, 158, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (159, 159, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (160, 160, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (161, 161, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (162, 162, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (163, 163, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (164, 164, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (165, 165, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (166, 166, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (167, 167, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (168, 168, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (169, 169, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (170, 170, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (171, 171, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (172, 172, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (173, 173, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (174, 174, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (175, 175, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (176, 176, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (177, 177, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (178, 178, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (179, 179, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (180, 180, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (181, 181, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (182, 182, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (183, 183, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (184, 184, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (185, 185, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (186, 186, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (187, 187, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (188, 188, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (189, 189, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (190, 190, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (191, 191, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (192, 192, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (193, 193, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (194, 194, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (195, 195, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (196, 196, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (197, 197, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (198, 198, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (199, 199, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (200, 200, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (201, 201, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (202, 202, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (203, 203, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (204, 204, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (205, 205, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (206, 206, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (207, 207, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (208, 208, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (209, 209, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (210, 210, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (211, 211, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (212, 212, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (213, 213, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (214, 214, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (215, 215, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (216, 216, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (217, 217, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (218, 218, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (219, 219, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (220, 220, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (221, 221, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (222, 222, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (223, 223, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (224, 224, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (225, 225, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (226, 226, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (227, 227, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (228, 228, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (229, 229, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (230, 230, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (231, 231, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (232, 232, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (233, 233, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (234, 234, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (235, 235, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (236, 236, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (237, 237, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (238, 238, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (239, 239, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (240, 240, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (241, 241, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (242, 242, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (243, 243, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (244, 244, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (245, 245, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (246, 246, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (247, 247, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (248, 248, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (249, 249, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (250, 250, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (251, 251, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (252, 252, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (253, 253, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (254, 254, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (255, 255, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (256, 256, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (257, 257, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (258, 258, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (259, 259, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (260, 260, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (261, 261, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (262, 262, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (263, 263, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (264, 264, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (265, 265, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (266, 266, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (267, 267, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (268, 268, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (269, 269, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (270, 270, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (271, 271, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (272, 272, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (273, 273, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (274, 274, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (275, 275, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (276, 276, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (277, 277, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (278, 278, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (279, 279, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (280, 280, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (281, 281, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (282, 282, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (283, 283, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (284, 284, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (285, 285, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (286, 286, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (287, 287, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (288, 288, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (289, 289, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (290, 290, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (291, 291, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (292, 292, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (293, 293, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (294, 294, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (295, 295, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (296, 296, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (297, 297, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (298, 298, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (299, 299, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (300, 300, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (301, 301, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (302, 302, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (303, 303, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (304, 304, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (305, 305, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (306, 306, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (307, 307, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (308, 308, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (309, 309, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (310, 310, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (311, 311, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (312, 312, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (313, 313, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (314, 314, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (315, 315, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (316, 316, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (317, 317, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (318, 318, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (319, 319, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (320, 320, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (321, 321, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (322, 322, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (323, 323, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (324, 324, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (325, 325, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (326, 326, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (327, 327, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (328, 328, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (329, 329, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (330, 330, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (331, 331, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (332, 332, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (333, 333, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (334, 334, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (335, 335, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (336, 336, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (337, 337, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (338, 338, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (339, 339, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (340, 340, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (341, 341, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (342, 342, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (343, 343, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (344, 344, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (345, 345, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (346, 346, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (347, 347, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (348, 348, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (349, 349, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (350, 350, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (351, 351, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (352, 352, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (353, 353, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (354, 354, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (355, 355, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (356, 356, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (357, 357, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (358, 358, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (359, 359, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (360, 360, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (361, 361, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (362, 362, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (363, 363, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (364, 364, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (365, 365, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (366, 366, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (367, 367, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (368, 368, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (369, 369, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (370, 370, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (371, 371, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (372, 372, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (373, 373, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (374, 374, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (375, 375, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (376, 376, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (377, 377, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (378, 378, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (379, 379, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (380, 380, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (381, 381, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (382, 382, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (383, 383, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (384, 384, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (385, 385, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (386, 386, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (387, 387, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (388, 388, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (389, 389, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (390, 390, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (391, 391, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (392, 392, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (393, 393, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (394, 394, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (395, 395, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (396, 396, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (397, 397, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (398, 398, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (399, 399, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (400, 400, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (401, 401, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (402, 402, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (403, 403, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (404, 404, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (405, 405, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (406, 406, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (407, 407, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (408, 408, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (409, 409, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (410, 410, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (411, 411, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (412, 412, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (413, 413, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (414, 414, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (415, 415, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (416, 416, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (417, 417, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (418, 418, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (419, 419, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (420, 420, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (421, 421, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (422, 422, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (423, 423, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (424, 424, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (425, 425, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (426, 426, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (427, 427, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (428, 428, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (429, 429, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (430, 430, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (431, 431, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (432, 432, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (433, 433, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (434, 434, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (435, 435, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (436, 436, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (437, 437, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (438, 438, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (439, 439, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (440, 440, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (441, 441, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (442, 442, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (443, 443, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (444, 444, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (445, 445, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (446, 446, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (447, 447, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (448, 448, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (449, 449, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (450, 450, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (451, 451, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (452, 452, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (453, 453, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (454, 454, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (455, 455, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (456, 456, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (457, 457, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (458, 458, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (459, 459, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (460, 460, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (461, 461, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (462, 462, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (463, 463, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (464, 464, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (465, 465, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (466, 466, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (467, 467, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (468, 468, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (469, 469, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (470, 470, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (471, 471, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (472, 472, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (473, 473, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (474, 474, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (475, 475, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (476, 476, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (477, 477, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (478, 478, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (479, 479, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (480, 480, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (481, 481, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (482, 482, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (483, 483, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (484, 484, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (485, 485, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (486, 486, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (487, 487, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (488, 488, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (489, 489, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (490, 490, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (491, 491, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (492, 492, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (493, 493, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (494, 494, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (495, 495, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (496, 496, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (497, 497, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (498, 498, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (499, 499, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (500, 500, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (501, 501, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (502, 502, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (503, 503, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (504, 504, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (505, 505, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (506, 506, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (507, 507, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (508, 508, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (509, 509, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (510, 510, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (511, 511, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (512, 512, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (513, 513, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (514, 514, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (515, 515, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (516, 516, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (517, 517, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (518, 518, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (519, 519, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (520, 520, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (521, 521, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (522, 522, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (523, 523, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (524, 524, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (525, 525, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (526, 526, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (527, 527, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (528, 528, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (529, 529, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (530, 530, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (531, 531, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (532, 532, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (533, 533, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (534, 534, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (535, 535, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (536, 536, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (537, 537, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (538, 538, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (539, 539, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (540, 540, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (541, 541, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (542, 542, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (543, 543, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (544, 544, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (545, 545, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (546, 546, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (547, 547, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (548, 548, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (549, 549, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (550, 550, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (551, 551, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (552, 552, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (553, 553, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (554, 554, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (555, 555, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (556, 556, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (557, 557, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (558, 558, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (559, 559, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (560, 560, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (561, 561, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (562, 562, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (563, 563, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (564, 564, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (565, 565, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (566, 566, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (567, 567, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (568, 568, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (569, 569, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (570, 570, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (571, 571, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (572, 572, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (573, 573, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (574, 574, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (575, 575, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (576, 576, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (577, 577, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (578, 578, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (579, 579, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (580, 580, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (581, 581, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (582, 582, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (583, 583, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (584, 584, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (585, 585, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (586, 586, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (587, 587, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (588, 588, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (589, 589, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (590, 590, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (591, 591, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (592, 592, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (593, 593, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (594, 594, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (595, 595, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (596, 596, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (597, 597, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (598, 598, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (599, 599, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (600, 600, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (601, 601, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (602, 602, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (603, 603, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (604, 604, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (605, 605, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (606, 606, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (607, 607, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (608, 608, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (609, 609, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (610, 610, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (611, 611, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (612, 612, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (613, 613, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (614, 614, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (615, 615, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (616, 616, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (617, 617, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (618, 618, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (619, 619, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (620, 620, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (621, 621, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (622, 622, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (623, 623, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (624, 624, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (625, 625, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (626, 626, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (627, 627, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (628, 628, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (629, 629, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (630, 630, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (631, 631, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (632, 632, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (633, 633, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (634, 634, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (635, 635, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (636, 636, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (637, 637, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (638, 638, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (639, 639, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (640, 640, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (641, 641, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (642, 642, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (643, 643, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (644, 644, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (645, 645, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (646, 646, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (647, 647, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (648, 648, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (649, 649, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (650, 650, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (651, 651, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (652, 652, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (653, 653, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (654, 654, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (655, 655, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (656, 656, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (657, 657, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (658, 658, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (659, 659, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (660, 660, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (661, 661, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (662, 662, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (663, 663, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (664, 664, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (665, 665, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (666, 666, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (667, 667, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (668, 668, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (669, 669, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (670, 670, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (671, 671, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (672, 672, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (673, 673, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (674, 674, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (675, 675, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (676, 676, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (677, 677, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (678, 678, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (679, 679, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (680, 680, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (681, 681, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (682, 682, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (683, 683, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (684, 684, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (685, 685, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (686, 686, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (687, 687, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (688, 688, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (689, 689, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (690, 690, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (691, 691, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (692, 692, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (693, 693, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (694, 694, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (695, 695, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (696, 696, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (697, 697, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (698, 698, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (699, 699, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (700, 700, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (701, 701, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (702, 702, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (703, 703, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (704, 704, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (705, 705, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (706, 706, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (707, 707, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (708, 708, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (709, 709, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (710, 710, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (711, 711, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (712, 712, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (713, 713, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (714, 714, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (715, 715, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (716, 716, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (717, 717, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (718, 718, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (719, 719, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (720, 720, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (721, 721, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (722, 722, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (723, 723, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (724, 724, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (725, 725, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (726, 726, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (727, 727, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (728, 728, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (729, 729, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (730, 730, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (731, 731, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (732, 732, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (733, 733, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (734, 734, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (735, 735, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (736, 736, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (737, 737, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (738, 738, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (739, 739, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (740, 740, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (741, 741, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (742, 742, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (743, 743, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (744, 744, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (745, 745, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (746, 746, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (747, 747, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (748, 748, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (749, 749, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (750, 750, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (751, 751, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (752, 752, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (753, 753, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (754, 754, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (755, 755, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (756, 756, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (757, 757, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (758, 758, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (759, 759, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (760, 760, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (761, 761, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (762, 762, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (763, 763, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (764, 764, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (765, 765, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (766, 766, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (767, 767, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (768, 768, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (769, 769, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (770, 770, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (771, 771, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (772, 772, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (773, 773, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (774, 774, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (775, 775, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (776, 776, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (777, 777, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (778, 778, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (779, 779, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (780, 780, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (781, 781, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (782, 782, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (783, 783, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (784, 784, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (785, 785, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (786, 786, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (787, 787, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (788, 788, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (789, 789, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (790, 790, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (791, 791, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (792, 792, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (793, 793, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (794, 794, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (795, 795, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (796, 796, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (797, 797, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (798, 798, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (799, 799, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (800, 800, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (801, 801, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (802, 802, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (803, 803, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (804, 804, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (805, 805, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (806, 806, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (807, 807, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (808, 808, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (809, 809, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (810, 810, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (811, 811, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (812, 812, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (813, 813, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (814, 814, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (815, 815, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (816, 816, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (817, 817, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (818, 818, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (819, 819, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (820, 820, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (821, 821, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (822, 822, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (823, 823, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (824, 824, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (825, 825, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (826, 826, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (827, 827, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (828, 828, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (829, 829, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (830, 830, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (831, 831, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (832, 832, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (833, 833, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (834, 834, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (835, 835, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (836, 836, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (837, 837, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (838, 838, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (839, 839, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (840, 840, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (841, 841, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (842, 842, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (843, 843, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (844, 844, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (845, 845, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (846, 846, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (847, 847, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (848, 848, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (849, 849, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (850, 850, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (851, 851, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (852, 852, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (853, 853, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (854, 854, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (855, 855, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (856, 856, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (857, 857, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (858, 858, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (859, 859, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (860, 860, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (861, 861, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (862, 862, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (863, 863, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (864, 864, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (865, 865, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (866, 866, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (867, 867, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (868, 868, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (869, 869, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (870, 870, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (871, 871, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (872, 872, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (873, 873, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (874, 874, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (875, 875, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (876, 876, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (877, 877, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (878, 878, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (879, 879, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (880, 880, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (881, 881, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (882, 882, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (883, 883, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (884, 884, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (885, 885, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (886, 886, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (887, 887, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (888, 888, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (889, 889, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (890, 890, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (891, 891, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (892, 892, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (893, 893, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (894, 894, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (895, 895, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (896, 896, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (897, 897, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (898, 898, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (899, 899, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (900, 900, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (901, 901, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (902, 902, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (903, 903, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (904, 904, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (905, 905, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (906, 906, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (907, 907, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (908, 908, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (909, 909, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (910, 910, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (911, 911, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (912, 912, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (913, 913, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (914, 914, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (915, 915, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (916, 916, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (917, 917, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (918, 918, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (919, 919, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (920, 920, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (921, 921, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (922, 922, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (923, 923, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (924, 924, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (925, 925, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (926, 926, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (927, 927, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (928, 928, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (929, 929, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (930, 930, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (931, 931, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (932, 932, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (933, 933, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (934, 934, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (935, 935, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (936, 936, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (937, 937, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (938, 938, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (939, 939, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (940, 940, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (941, 941, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (942, 942, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (943, 943, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (944, 944, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (945, 945, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (946, 946, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (947, 947, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (948, 948, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (949, 949, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (950, 950, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (951, 951, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (952, 952, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (953, 953, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (954, 954, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (955, 955, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (956, 956, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (957, 957, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (958, 958, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (959, 959, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (960, 960, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (961, 961, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (962, 962, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (963, 963, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (964, 964, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (965, 965, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (966, 966, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (967, 967, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (968, 968, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (969, 969, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (970, 970, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (971, 971, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (972, 972, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (973, 973, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (974, 974, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (975, 975, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (976, 976, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (977, 977, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (978, 978, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (979, 979, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (980, 980, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (981, 981, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (982, 982, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (983, 983, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (984, 984, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (985, 985, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (986, 986, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (987, 987, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (988, 988, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (989, 989, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (990, 990, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (991, 991, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (992, 992, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (993, 993, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (994, 994, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (995, 995, 'In Progress');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (996, 996, 'Failed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (997, 997, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (998, 998, 'Enrolled');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (999, 999, 'Completed');
insert into EmployeeTraining (TrainingID, EmployeeID, Status) values (1000, 1000, 'Failed');
